version: "3.3"

services:
  nats:
    image: nats:1.3.0
    container_name: nats
    ports:
      - "4222:4222"   
      - "6222:6222"  
      - "8222:8222"
    restart: always

  api:
    image: gasiepgodoy/moleculer:api-v1.0.8
    container_name: api-v1.0.8
    ports:
      - "3000:3000"   # Porta para conexões de cliente
    restart: always
    environment:
      - TRANSPORTER_URL=nats://nats:4222
      - API_PORT=3000
    depends_on:
      - nats

  greeter:
    image: gasiepgodoy/moleculer:greeter-v1.0.8
    container_name: greeter-v1.0.8
    restart: always
    environment:
      - TRANSPORTER_URL=nats://nats:4222
    depends_on:
      - nats
