version: "3.3"

services:
  nats:
    image: nats:2.6.1
    container_name: nats
    env_file:
      - .env
    ports:
      - "${HOST_NATS_MAIN_PORT}:${CONTAINER_NATS_MAIN_PORT}"
      - "${HOST_NATS_ROUTE_PORT}:${CONTAINER_NATS_ROUTE_PORT}"
      - "${HOST_NATS_MONITOR_PORT}:${CONTAINER_NATS_MONITOR_PORT}"
    restart: always

  api:
    image: gasiepgodoy/moleculer:api-v1.0.0
    container_name: api
    env_file:
      - .env
    ports:
      - "${HOST_API_MAIN_PORT}:${CONTAINER_API_MAIN_PORT}"
    restart: always
    depends_on:
      - nats

  greeter:
    image: gasiepgodoy/moleculer:greeter-v1.0.0
    container_name: greeter
    env_file:
      - .env
    restart: always
    depends_on:
      - nats
