# This compose executes and sets up all applications on a single device.If you want to run distributed in a distributed manner, just copy this compose, and comment on the parties you do not want, and perform it.

version: "3.3"

services:

  # Status: pending
  # portainer:
  #   container_name: portainer
  #   image: portainer/portainer-ce:2.16.1
  #   ports:
  #     - "8000:8000"
  #     - "9000:9000"
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ./data:/data
  #   environment:
  #   - ADMIN_USERNAME=pi
  #   - ADMIN_PASSWORD=raspberryportainer

  # Status: resolved
  # portainer_edge_agent:
  #   image: portainer/agent:2.15.1
  #   container_name: portainer_edge_agent
  #   restart: always
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/volumes:/var/lib/docker/volumes
  #     - /:/host
  #     - portainer_agent_data:/data
  #   environment:
  #     - CAP_HOST_MANAGEMENT=1
  #     - EDGE=1
  #     - EDGE_ID=5953ca0f-c638-4bff-9be1-b5bba32825f2
  #     - EDGE_KEY=aHR0cDovLzE5Mi4xNjguMS42OjkwMDB8MTkyLjE2OC4xLjY6ODAwMHxmOTo1ZTo0YTplOTo0YzplNzozNTo2NjowNTo2MTpjNzoxMDoxZDpmMjo0NDpmMXwyMg
  #     - EDGE_INSECURE_POOL=1

  # Status: resolved
  # nats:
  #   image: nats:1.3.0
  #   container_name: nats
  #   ports:
  #     - "4222:4222"
  #     - "6222:6222"
  #     - "8222:8222"
  #   restart: always

  # Status: resolved
  # api:
  #   image: gasiepgodoy/moleculer:api-v1.0.8
  #   container_name: api
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   environment:
  #     - TRANSPORTER_URL=nats://nats:4222
  #     - API_PORT=3000
  #   depends_on:
  #     - nats

  # Status: resolved
  # greeter:
  #   image: gasiepgodoy/moleculer:greeter-v1.0.8
  #   container_name: greeter
  #   restart: always
  #   environment:
  #     - TRANSPORTER_URL=nats://nats:4222
  #   depends_on:
  #     - nats

  # Status: resolved
  # grafana:

  # Status: resolved
  # influxdb:

  # Status: resolved
  # node_red:

  # Status: resolved
  # open_plc:

  # Status: resolved
  # 4diac:

  # Status: pending
  # aasx_server:
  #   container_name: aasx_server
  #   image: docker.io/adminshellio/aasx-server-blazor-for-demo-arm32:main
  #   restart: always
  #   ports:
  #     - 5001:5001
  #   environment:
  #     - Kestrel__Endpoints__Http__Url=http://*:5001
  #   volumes:
  #     - ./aasxs:/AasxServerBlazor/aasxs
  #   command: --no-security --data-path /AasxServerBlazor/aasxs --external-blazor http://localhost

  # Status: pending
  fit116_daq:
    image: gasiepgodoy/moleculer:fit116_v1.0.3
    container_name: fit116_daq
    ports:
      - "26116:26116"
    environment:
      - NAME=fit116_daq
      - TRANSPORTER=nats://192.168.1.201:4222
      - I2C_MEM_OPTO_IN_VAL=3
      - I2C_MEM_U0_10_OUT_VAL1=4
      - I2C_MEM_I4_20_OUT_VAL1=12
      - I2C_MEM_OD_PWM1=20
      - I2C_MEM_U0_10_IN_VAL1=28
      - I2C_MEM_I4_20_IN_VAL1=44
      - I2C_RTC_YEAR_ADD=70
      - DEFAULT_HW_ADD=80
      - I2C_MEM_DIAG_TEMPERATURE=114
      - MILLISECONDS=150
      - STACK=0
      - CHANNEL=4
      - NODE_NAMESPACE=3
      - NODE_IDENTIFIER=504
      - OPCUA_PORT=26116
    restart: always
    devices:
      - /dev/i2c-1:/dev/i2c-1
    mem_limit: 256m
  # Status: pending
  # lit125_daq:

  # Status: pending
  # pit118_daq:

  # Status: pending
  # pit129_daq:

  # Status: pending
  # fic116_pid4:

  # Status: pending
  # lic125_pid4:

  # Status: pending
  # pic118_pid4:

  # Status: pending
  # pic129_pid4:

  # Status: pending
  # lv122_daq:

  # Status: pending
  # p1_daq:

  # Status: pending
  # p2_daq:


  # volumes:
  #   portainer_agent_data:
